d /var/opt/sentinelone/log            0755 root root -
d /var/opt/sentinelone/configuration  0755 root root -
L /opt/sentinelone/log           -    -    -    - /var/opt/sentinelone/log
L /opt/sentinelone/configuration  -   -    -    - /var/opt/sentinelone/configuration
