d /var/sentinelone 0755 root root -
C /var/sentinelone/configuration - - - - /usr/lib/opt/sentinelone/configuration
C /var/sentinelone/log - - - - /usr/lib/opt/sentinelone/log
C /var/sentinelone/crash_dumps - - - - /usr/lib/opt/sentinelone/crash_dumps
C /var/sentinelone/assets - - - - /usr/lib/opt/sentinelone/assets
C /var/sentinelone/.storage - - - - /usr/lib/opt/sentinelone/.storage
